<?php
// Shared documentation data for DISPATCH.
// Used by: index.php (inline fullscreen doc modal), video_docs.php (doc cards + modal)
//
// Defines $videoCatalog (metadata for every feature/module) and $videoDocs
// (long-form documentation text keyed by module id). Include this file once
// before using either array.

if (!isset($videoCatalog)) {
    $videoCatalog = [
        ['id' => 'dashboard', 'title' => 'Dashboard', 'desc' => 'Overview and statistics walkthrough', 'category' => 'Main', 'duration' => '2:30', 'src' => 'videos/dashboard.mp4'],
        ['id' => 'my-loads', 'title' => 'My Loads', 'desc' => 'Create, assign and track loads through dispatch', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/my-loads.mp4'],
        ['id' => 'my-trucks', 'title' => 'My Trucks', 'desc' => 'Add, view and manage your trucks', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/my-trucks.mp4'],
        ['id' => 'my-trailers', 'title' => 'My Trailers', 'desc' => 'Add, view and manage your trailers', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/my-trailers.mp4'],
        ['id' => 'driver-devices', 'title' => 'Driver Devices', 'desc' => 'Manage driver devices and ELD connections', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/driver-devices.mp4'],
        ['id' => 'my-drivers', 'title' => 'My Drivers', 'desc' => 'View and manage your drivers', 'category' => 'Operations', 'duration' => '3:45', 'src' => 'videos/how-to-register-new-drivers.mp4'],
        ['id' => 'my-customers', 'title' => 'My Customers', 'desc' => 'Add, view and manage your customers', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/my-customers.mp4'],
        ['id' => 'my-shippers-list', 'title' => 'My Shippers List', 'desc' => 'Manage your list of shippers', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/my-shippers-list.mp4'],
        ['id' => 'my-consignee-lists', 'title' => 'My Consignee Lists', 'desc' => 'Manage your consignee lists and locations', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/my-consignee-lists.mp4'],
        ['id' => 'my-brokers', 'title' => 'My Brokers', 'desc' => 'Add and manage your brokers', 'category' => 'Operations', 'duration' => '', 'src' => 'videos/my-brokers.mp4'],
        ['id' => 'truck-lease-pricing', 'title' => 'Truck Lease Pricing', 'desc' => 'Review and configure lease pricing', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/truck-lease-pricing.mp4'],
        ['id' => 'truck-rentals', 'title' => 'Truck Rentals', 'desc' => 'Manage truck rentals and equipment', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/truck-rentals.mp4'],
        ['id' => 'lease-agreements', 'title' => 'Lease Agreements', 'desc' => 'Create, sign and track lease agreements', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/lease-agreements.mp4'],
        ['id' => 'hire-drivers', 'title' => 'Hire Drivers', 'desc' => 'Recruit and onboard new drivers', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/hire-drivers.mp4'],
        ['id' => 'job-postings', 'title' => 'Job Postings', 'desc' => 'Create and manage driver job postings', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/job-postings.mp4'],
        ['id' => 'external-drivers', 'title' => 'External Drivers', 'desc' => 'Manage external and owner-operator drivers', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/external-drivers.mp4'],
        ['id' => 'shout-out-scripts', 'title' => 'Shout Out Scripts', 'desc' => 'Ready-made scripts for your marketing', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/shout-out-scripts.mp4'],
        ['id' => 'shout-out-vlogs', 'title' => 'Shout Out Vlogs', 'desc' => 'Shout out vlog examples and walkthroughs', 'category' => 'Fleet', 'duration' => '', 'src' => 'videos/shout-out-vlogs.mp4'],
        ['id' => 'accounting', 'title' => 'Accounting', 'desc' => 'Manage accounting and financial records', 'category' => 'Finance', 'duration' => '', 'src' => 'videos/accounting.mp4'],
        ['id' => 'my-payroll', 'title' => 'My Payroll', 'desc' => 'Run and manage payroll', 'category' => 'Finance', 'duration' => '', 'src' => 'videos/my-payroll.mp4'],
        ['id' => 'my-factoring-company', 'title' => 'My Factoring Company', 'desc' => 'Connect and manage your factoring company', 'category' => 'Finance', 'duration' => '', 'src' => 'videos/my-factoring-company.mp4'],
        ['id' => 'fuel-reports', 'title' => 'Fuel Reports', 'desc' => 'View fuel spending reports and analytics', 'category' => 'Finance', 'duration' => '', 'src' => 'videos/fuel-reports.mp4'],
        ['id' => 'my-fuel-cards', 'title' => 'My Fuel Cards', 'desc' => 'Manage fuel cards and spending limits', 'category' => 'Finance', 'duration' => '', 'src' => 'videos/my-fuel-cards.mp4'],
        ['id' => 'loans-cash-advance', 'title' => 'Loans/Cash Advance', 'desc' => 'Apply for and track loans and cash advances', 'category' => 'Finance', 'duration' => '', 'src' => 'videos/loans-cash-advance.mp4'],
        ['id' => 'api-integration-keys', 'title' => 'API Integration Keys', 'desc' => 'Generate and manage API integration keys', 'category' => 'Finance', 'duration' => '', 'src' => 'videos/api-integration-keys.mp4'],
        ['id' => 'my-fleet', 'title' => 'My Fleet', 'desc' => 'Monitor your fleet safety and compliance', 'category' => 'Safety', 'duration' => '', 'src' => 'videos/my-fleet.mp4'],
        ['id' => 'emergency-monitoring', 'title' => 'Emergency Monitoring', 'desc' => 'Set up and respond to emergency alerts', 'category' => 'Safety', 'duration' => '', 'src' => 'videos/emergency-monitoring.mp4'],
        ['id' => 'safety-assessments', 'title' => 'Safety Assessments', 'desc' => 'Run and review safety assessments', 'category' => 'Safety', 'duration' => '', 'src' => 'videos/safety-assessments.mp4'],
        ['id' => 'maintenance-monitoring', 'title' => 'Maintenance Monitoring', 'desc' => 'Monitor maintenance and vehicle health', 'category' => 'Safety', 'duration' => '', 'src' => 'videos/maintenance-monitoring.mp4'],
        ['id' => 'safety-violations', 'title' => 'Safety Violations', 'desc' => 'Safety-related compliance issues', 'category' => 'Safety', 'duration' => '', 'src' => 'videos/safety-violations.mp4'],
        ['id' => 'compliance-monitoring', 'title' => 'Compliance Monitoring', 'desc' => 'Track compliance metrics in real time', 'category' => 'Compliance', 'duration' => '', 'src' => 'videos/compliance-monitoring.mp4'],
        ['id' => 'compliance-software-options', 'title' => 'Compliance Software Options', 'desc' => 'Explore compliance software integrations', 'category' => 'Compliance', 'duration' => '', 'src' => 'videos/compliance-software-options.mp4'],
        ['id' => 'drug-alcohol-testing', 'title' => 'Drug & Alcohol Testing', 'desc' => 'Manage drug and alcohol testing programs', 'category' => 'Compliance', 'duration' => '', 'src' => 'videos/drug-alcohol-testing.mp4'],
        ['id' => 'violations', 'title' => 'Violations', 'desc' => 'Track compliance violations', 'category' => 'Compliance', 'duration' => '', 'src' => 'videos/violations.mp4'],
        ['id' => 'driver-violations', 'title' => 'Driver Violations', 'desc' => 'Driver-specific violations', 'category' => 'Compliance', 'duration' => '', 'src' => 'videos/driver-violations.mp4'],
        ['id' => 'vehicle-violations', 'title' => 'Vehicle Violations', 'desc' => 'Vehicle-related violations', 'category' => 'Compliance', 'duration' => '', 'src' => 'videos/vehicle-violations.mp4'],
        ['id' => 'hos', 'title' => 'HOS', 'desc' => 'Hours of Service compliance', 'category' => 'Compliance', 'duration' => '', 'src' => 'videos/hos.mp4'],
        ['id' => 'notifications', 'title' => 'Notifications', 'desc' => 'Real-time alerts and updates', 'category' => 'Account', 'duration' => '', 'src' => 'videos/notifications.mp4'],
        ['id' => 'activity', 'title' => 'Activity', 'desc' => 'System activity logs', 'category' => 'Account', 'duration' => '', 'src' => 'videos/activity.mp4'],
        ['id' => 'maintenance', 'title' => 'Maintenance', 'desc' => 'Vehicle maintenance scheduling', 'category' => 'Account', 'duration' => '', 'src' => 'videos/maintenance.mp4'],
        ['id' => 'drug-alcohol', 'title' => 'Drug & Alcohol', 'desc' => 'Testing programs and records', 'category' => 'Account', 'duration' => '', 'src' => 'videos/drug-alcohol.mp4'],
        ['id' => 'documents', 'title' => 'Documents', 'desc' => 'Centralized document management', 'category' => 'Account', 'duration' => '', 'src' => 'videos/documents.mp4'],
        ['id' => 'permit-insurance', 'title' => 'Permit & Insurance', 'desc' => 'Permits, licenses and insurance', 'category' => 'Account', 'duration' => '', 'src' => 'videos/permit-insurance.mp4'],
        ['id' => 'reporting', 'title' => 'Reporting', 'desc' => 'Reports and operational insights', 'category' => 'Account', 'duration' => '', 'src' => 'videos/reporting.mp4'],
        ['id' => 'safety', 'title' => 'Safety', 'desc' => 'Safety metrics and risk management', 'category' => 'Account', 'duration' => '', 'src' => 'videos/safety.mp4'],
        ['id' => 'settings', 'title' => 'Settings', 'desc' => 'Configure and customize the system', 'category' => 'Account', 'duration' => '', 'src' => 'videos/settings.mp4'],
        ['id' => 'login-signup-tutorial', 'title' => 'Login & Sign Up', 'desc' => 'Account creation and secure login', 'category' => 'Account', 'duration' => '', 'src' => 'videos/login-signup-tutorial.mp4']
    ];
}

if (!isset($videoDocs)) {
    $videoDocs = [
        'dashboard' => 'The Dashboard is the central command center of DISPATCH. It gives you a real-time overview of your operations, including active loads, driver status, fleet health, and key performance indicators. Use it to monitor daily activity, identify bottlenecks, and make quick decisions without navigating through multiple screens.',
        'my-loads' => 'My Loads is where you create, assign, and track every shipment in your dispatch pipeline. You can build new loads, assign drivers and trucks, update statuses, and view load details from pickup to delivery. It keeps your operation organized and ensures loads move on time.',
        'my-trucks' => 'My Trucks lets you add, view, and manage all trucks in your fleet. Record vehicle details, maintenance history, assigned drivers, and lease or rental information so you always know which equipment is available and road-ready.',
        'my-trailers' => 'My Trailers gives you a dedicated view for managing trailers across your fleet. Track ownership, inspection dates, assignments, and capacity so dispatch and safety teams have accurate trailer data for every load.',
        'driver-devices' => 'Driver Devices helps you manage ELD connections, mobile devices, and other hardware your drivers use. It ensures devices are properly paired, synced, and compliant with logging and tracking requirements.',
        'my-drivers' => 'My Drivers is the hub for managing your driver workforce. Add driver profiles, store license and medical card details, track hiring status, and view assigned trucks so your team stays compliant and qualified.',
        'my-customers' => 'My Customers stores customer profiles, billing details, and contact information. Use it to keep track of shipping partners, invoice addresses, and special requirements for each customer.',
        'my-shippers-list' => 'My Shippers List centralizes your recurring shipping locations. Save shipper names, addresses, and contact details so dispatchers can quickly select origin points when building loads.',
        'my-consignee-lists' => 'My Consignee Lists stores all delivery destination information. Maintain consignee addresses, hours, and instructions to improve routing and reduce delivery errors.',
        'my-brokers' => 'My Brokers helps you add and manage freight broker relationships. Store broker names, contact info, and notes so your team can quickly reference broker details during load negotiations.',
        'truck-lease-pricing' => 'Truck Lease Pricing allows you to review and configure lease rates and payment terms for your equipment. Use it to compare lease options, set pricing, and understand the financial impact of each lease agreement.',
        'truck-rentals' => 'Truck Rentals manages rental equipment and contracts. Track rental periods, costs, and return dates so rented trucks stay integrated with dispatch and accounting.',
        'lease-agreements' => 'Lease Agreements lets you create, sign, and track lease documents digitally. Store signed contracts, renewal dates, and terms so fleet and finance teams always have the latest agreement details.',
        'hire-drivers' => 'Hire Drivers streamlines driver recruitment and onboarding. Track applicants, collect documents, schedule interviews, and move candidates through the hiring pipeline efficiently.',
        'job-postings' => 'Job Postings lets you create and manage driver job openings. Post openings, track applications, and update hiring status so your recruiting efforts stay organized and visible.',
        'external-drivers' => 'External Drivers helps you manage owner-operators and contracted drivers who are not direct employees. Track contact information, equipment, and independent contractor status alongside your fleet.',
        'shout-out-scripts' => 'Shout Out Scripts provides ready-made marketing and recruiting scripts. Use these templates for social media, email, or phone outreach to attract drivers and promote your brand.',
        'shout-out-vlogs' => 'Shout Out Vlogs offers video examples and walkthroughs for creating driver-focused content. Learn how to produce effective vlogs that showcase your fleet and recruit talent.',
        'accounting' => 'Accounting keeps your financial records organized. Track invoices, payments, expenses, and profit so your operation has a clear view of its financial health.',
        'my-payroll' => 'My Payroll lets you run and manage driver and staff payroll. Calculate pay, track hours, and process payments while staying aligned with accounting records.',
        'my-factoring-company' => 'My Factoring Company connects you to invoice factoring services. Manage factoring provider details, submit invoices, and track advances to improve cash flow.',
        'fuel-reports' => 'Fuel Reports shows fuel spending, usage trends, and efficiency analytics. Use this data to identify waste, optimize routes, and manage fuel card spending.',
        'my-fuel-cards' => 'My Fuel Cards lets you manage fuel card assignments and spending limits. Track cardholders, set limits, and monitor transactions to control fuel costs.',
        'loans-cash-advance' => 'Loans and Cash Advance helps you apply for and track working capital. Record loan details, repayment schedules, and advance requests so cash flow needs are documented.',
        'api-integration-keys' => 'API Integration Keys lets you generate and manage keys for connecting DISPATCH with other systems. Control access and track which integrations are active.',
        'my-fleet' => 'My Fleet provides a safety and compliance overview of all your vehicles and drivers. Track inspections, violations, CSA scores, and preventive maintenance to keep your fleet safe and roadworthy.',
        'emergency-monitoring' => 'Emergency Monitoring helps you set up and respond to critical driver and vehicle alerts. Configure notification rules, monitor panic events, and coordinate emergency response.',
        'safety-assessments' => 'Safety Assessments lets you run and review driver and vehicle safety reviews. Schedule assessments, record results, and take action on any safety concerns.',
        'maintenance-monitoring' => 'Maintenance Monitoring tracks vehicle health and service schedules. Log repairs, schedule preventive maintenance, and set reminders to keep equipment in top condition.',
        'safety-violations' => 'Safety Violations records and tracks incidents that affect your safety score. Review violation details, assign corrective actions, and monitor resolution progress.',
        'compliance-monitoring' => 'Compliance Monitoring gives you a real-time view of regulatory compliance. Track HOS, inspections, and certifications to avoid fines and out-of-service risk.',
        'compliance-software-options' => 'Compliance Software Options lets you explore and configure integrations with ELD and compliance tools. Choose the right providers and sync data for accurate compliance reporting.',
        'drug-alcohol-testing' => 'Drug and Alcohol Testing manages testing programs and driver records. Track testing schedules, results, and program membership to meet DOT and company requirements.',
        'violations' => 'Violations tracks all compliance-related incidents across your operation. Review details, assign responsibility, and manage the resolution process from a single view.',
        'driver-violations' => 'Driver Violations focuses on citations and incidents tied to individual drivers. Monitor driver history, take corrective action, and track improvements over time.',
        'vehicle-violations' => 'Vehicle Violations tracks citations and defects tied to specific trucks or trailers. Use it to prioritize repairs and improve your fleet roadside inspection record.',
        'hos' => 'HOS, or Hours of Service, tracks driver duty and rest rules. Monitor on-duty time, breaks, and daily limits to ensure compliance and prevent driver fatigue.',
        'notifications' => 'Notifications delivers real-time alerts for loads, drivers, vehicles, and compliance events. Customize what you receive so important updates never get missed.',
        'activity' => 'Activity keeps a detailed log of system events and user actions. Use it for auditing, troubleshooting, and understanding how your team uses DISPATCH.',
        'maintenance' => 'Maintenance schedules and tracks vehicle maintenance tasks. Plan oil changes, inspections, and repairs so your fleet stays reliable and compliant.',
        'drug-alcohol' => 'Drug and Alcohol records testing data and program details. Maintain DOT compliance by tracking testing status, results, and program enrollments.',
        'documents' => 'Documents gives you a centralized place to store and manage permits, licenses, insurance, and other important files. Organize files by driver or vehicle and access them quickly.',
        'permit-insurance' => 'Permit and Insurance tracks registration, permits, and insurance certificates. Store expiration dates and upload documents so your fleet never runs out of coverage.',
        'reporting' => 'Reporting provides pre-built and custom reports for operations, safety, and finance. Generate insights that help you make data-driven decisions.',
        'safety' => 'Safety is the central place for safety metrics and risk management. Monitor accident rates, training status, and violation trends to build a stronger safety culture.',
        'settings' => 'Settings lets you configure your DISPATCH experience. Manage users, preferences, notifications, and system-wide options to match your workflow.',
        'login-signup-tutorial' => 'Login and Sign Up walks new users through creating an account and signing in securely. Learn how to set credentials, recover access, and protect your account.'
    ];
}
